// Mock data for hospitals
export const mockHospitals = [
  {
    id: "1",
    name: "Memorial General Hospital",
    image:
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
    location: "New York, NY",
    rating: 4.8,
    specializations: ["Cardiology", "Neurology", "Orthopedics", "Oncology"],
    phone: "(212) 555-1234",
    address: "1000 Broadway, New York, NY 10001",
    operatingHours: {
      Monday: "8:00 AM - 8:00 PM",
      Tuesday: "8:00 AM - 8:00 PM",
      Wednesday: "8:00 AM - 8:00 PM",
      Thursday: "8:00 AM - 8:00 PM",
      Friday: "8:00 AM - 6:00 PM",
      Saturday: "9:00 AM - 3:00 PM",
      Sunday: "Closed",
    },
    resources: {
      beds: { total: 300, available: 60 },
      icu: { total: 50, available: 12 },
      specialists: [
        { specialty: "Cardiology", count: 15 },
        { specialty: "Neurology", count: 10 },
        { specialty: "Orthopedics", count: 8 },
      ],
    },
    staff: [
      { id: "1", name: "Dr. John Carter", role: "Chief Cardiologist", contact: "john.carter@example.com" },
      { id: "2", name: "Dr. Lisa Brown", role: "Neurologist", contact: "lisa.brown@example.com" },
      { id: "3", name: "Nurse James Wilson", role: "Head Nurse", contact: "james.wilson@example.com" },
    ],
    contactEmail: "info@memorialgeneral.com",
    website: "www.memorialgeneral.com",
  },
  {
    id: "2",
    name: "City Medical Center",
    image:
      "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1173&q=80",
    location: "Boston, MA",
    rating: 4.6,
    specializations: ["Pediatrics", "Obstetrics", "Cardiology", "Emergency Medicine"],
    phone: "(617) 555-5678",
    address: "500 Main St, Boston, MA 02108",
    operatingHours: {
      Monday: "7:00 AM - 9:00 PM",
      Tuesday: "7:00 AM - 9:00 PM",
      Wednesday: "7:00 AM - 9:00 PM",
      Thursday: "7:00 AM - 9:00 PM",
      Friday: "7:00 AM - 7:00 PM",
      Saturday: "8:00 AM - 2:00 PM",
      Sunday: "Closed",
    },
    resources: {
      beds: { total: 250, available: 40 },
      icu: { total: 40, available: 8 },
      specialists: [
        { specialty: "Pediatrics", count: 10 },
        { specialty: "Obstetrics", count: 7 },
        { specialty: "Cardiology", count: 5 },
      ],
    },
    staff: [
      { id: "4", name: "Dr. Emily White", role: "Pediatrician", contact: "emily.white@example.com" },
      { id: "5", name: "Dr. Mark Roberts", role: "Emergency Medicine Specialist", contact: "mark.roberts@example.com" },
      { id: "6", name: "Nurse Susan Taylor", role: "Lead Nurse", contact: "susan.taylor@example.com" },
    ],
    contactEmail: "info@citymedicalcenter.com",
    website: "www.citymedicalcenter.com",
  },
  {
    id: "3",
    name: "Westside Health Institute",
    image:
      "https://images.unsplash.com/photo-1516549655169-df83a0774514?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    location: "Los Angeles, CA",
    rating: 4.5,
    specializations: ["Orthopedics", "Sports Medicine", "Rehabilitation", "Pain Management"],
    phone: "(310) 555-9012",
    address: "789 Sunset Blvd, Los Angeles, CA 90001",
    operatingHours: {
      Monday: "9:00 AM - 7:00 PM",
      Tuesday: "9:00 AM - 7:00 PM",
      Wednesday: "9:00 AM - 7:00 PM",
      Thursday: "9:00 AM - 7:00 PM",
      Friday: "9:00 AM - 5:00 PM",
      Saturday: "Closed",
      Sunday: "Closed",
    },
    resources: {
      beds: { total: 200, available: 35 },
      icu: { total: 30, available: 5 },
      specialists: [
        { specialty: "Orthopedics", count: 12 },
        { specialty: "Sports Medicine", count: 9 },
        { specialty: "Rehabilitation", count: 7 },
      ],
    },
    staff: [
      { id: "7", name: "Dr. Olivia Martinez", role: "Orthopedic Surgeon", contact: "olivia.martinez@example.com" },
      { id: "8", name: "Dr. Tom Anderson", role: "Pain Management Specialist", contact: "tom.anderson@example.com" },
      { id: "9", name: "Nurse Amanda Lopez", role: "Senior Nurse", contact: "amanda.lopez@example.com" },
    ],
    contactEmail: "info@westsidehealth.com",
    website: "www.westsidehealth.com",
  },
];


// Mock data for patients
export const mockPatients = [
  {
    id: '1',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '(555) 123-4567',
    age: 42,
    bloodType: 'A+',
    medicalHistory: 'Hypertension, Allergies to penicillin, Previous knee surgery in 2020',
  },
  {
    id: '2',
    name: 'Robert Johnson',
    email: 'robert.johnson@example.com',
    phone: '(555) 234-5678',
    age: 65,
    bloodType: 'O-',
    medicalHistory: 'Type 2 Diabetes, Coronary artery disease, Cholesterol medication',
  },
  {
    id: '3',
    name: 'Maria Garcia',
    email: 'maria.garcia@example.com',
    phone: '(555) 345-6789',
    age: 35,
    bloodType: 'B+',
    medicalHistory: 'Asthma, Seasonal allergies, No major surgeries',
  },
  {
    id: '4',
    name: 'David Lee',
    email: 'david.lee@example.com',
    phone: '(555) 456-7890',
    age: 28,
    bloodType: 'AB+',
    medicalHistory: 'Fractured wrist (2019), Appendectomy (2015), No chronic conditions',
  },
  {
    id: '5',
    name: 'Sarah Williams',
    email: 'sarah.williams@example.com',
    phone: '(555) 567-8901',
    age: 52,
    bloodType: 'A-',
    medicalHistory: 'Hypothyroidism, Migraines, Knee replacement (2021)',
  },
  {
    id: '6',
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    phone: '(555) 678-9012',
    age: 71,
    bloodType: 'O+',
    medicalHistory: 'Atrial fibrillation, Hypertension, Hip replacement (2018), Pacemaker',
  },
  {
    id: '7',
    name: 'Jennifer Davis',
    email: 'jennifer.davis@example.com',
    phone: '(555) 789-0123',
    age: 39,
    bloodType: 'B-',
    medicalHistory: 'Anxiety disorder, GERD, No major surgeries',
  },
  {
    id: '8',
    name: 'James Wilson',
    email: 'james.wilson@example.com',
    phone: '(555) 890-1234',
    age: 45,
    bloodType: 'A+',
    medicalHistory: 'Lower back pain, Herniated disc (L4-L5), Physical therapy ongoing',
  },
];